version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true' #It avoids to depend on ZookeperE
      CLUSTER_ID: '1L6GN7NgHu-eAKFfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller # node number 1 works as controller and broker at the same time.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 #2@kafka:9093,3@kafka:9093.. nodeNumber@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # No backup, just one copy. Ex: For a cluster of 3 nodes, default value is 3.

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 #One door for clients and one for controllers.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs # Where to store (Data files, Broker logs, Controller metadata)

    volumes:
      - kafka_kraft:/var/lib/kafka/data

volumes:
  kafka_kraft: